<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>PTLControl.App</AssemblyName>
    <RootNamespace>PTLControl</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PTLControl.Compat\PTLControl.Compat.csproj" />
  </ItemGroup>

  <Target Name="CopyHardwareHost" AfterTargets="Build">
    <Copy SourceFiles="..\PTLControl.HardwareHost\bin\$(Configuration)\net472\PTLControl.HardwareHost.exe"
          DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="idemia.png" />
  </ItemGroup>

</Project>
