<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PTLDemo.VBTest</RootNamespace>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PTLControl.Compat">
      <HintPath>..\PTLDemo.Compat\bin\Release\net472\PTLControl.Compat.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\PTLDemo.Compat\bin\Release\net472\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
